In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

In [2]:
guns15_17 = pd.read_csv("Cleaned-gun-deaths.csv", low_memory=False)

In [17]:
guns15_17.head()

,Unnamed: 0,Resident_Status,Month_Of_Death,Sex,Age,Age_Group,Place_Of_Death,Marital_Status,DOW_of_Death,Data_Year,Injured_At_Work,Manner_Of_Death,Activity_Code,Place_Of_Causal_Injury,Race,Hispanic_Origin,Causes_of_Death,ICD10
0,0,Residents,January,M,48,45 - 54,Decendents Home,M,Saturday,2015,N,Suicide,Other Activity,Home,White,Non - Hispanic white,suicide by firearms,suicide
1,1,Residents,January,F,19,15 - 24,Other,S,Tuesday,2015,N,Suicide,Other Activity,Other Places,White,Non - Hispanic white,suicide by firearms,suicide
2,2,Residents,January,M,33,25 - 34,Decendents Home,M,Sunday,2015,N,Suicide,Other Activity,Home,White,Non - Hispanic white,suicide by firearms,suicide
3,3,Inter_state_NR,January,F,23,15 - 24,Outpatient Hospital,S,Tuesday,2015,N,Homicide,Other Activity,Home,Black,Non - Hispanic black,Assault (homicide) by discharge of firearms,Assault (homicide)
4,4,Residents,January,F,40,35 - 44,Other,D,Tuesday,2015,N,Suicide,Other Activity,Other Places,White,Non - Hispanic white,suicide by firearms,suicide

In [4]:
guns15_17.count()

Unnamed: 0                115065
Resident_Status           115065
Month_Of_Death            115065
Sex                       115065
Age                       115065
Age_Group                 115065
Place_Of_Death            115065
Marital_Status            115065
DOW_of_Death              115065
Data_Year                 115065
Injured_At_Work           115065
Manner_Of_Death           115065
Activity_Code             115065
Place_Of_Causal_Injury    115065
Race                      115065
Hispanic_Origin           115065
Causes_of_Death           115065
ICD10                     115065
dtype: int64

In [5]:
guns15_17byrace = guns15_17.groupby(['Race'])

In [11]:
guns15_17byrace.count()

,Unnamed: 0,Resident_Status,Month_Of_Death,Sex,Age,Age_Group,Place_Of_Death,Marital_Status,DOW_of_Death,Data_Year,Injured_At_Work,Manner_Of_Death,Activity_Code,Place_Of_Causal_Injury,Hispanic_Origin,Causes_of_Death,ICD10
Race,,,,,,,,,,,,,,,,,
American Indian,1271,1271,1271,1271,1271,1271,1271,1271,1271,1271,1271,1271,1271,1271,1271,1271,1271
Asian Indian,226,226,226,226,226,226,226,226,226,226,226,226,226,226,226,226,226
Asian or Pacific Islander,618,618,618,618,618,618,618,618,618,618,618,618,618,618,618,618,618
Black,29522,29522,29522,29522,29522,29522,29522,29522,29522,29522,29522,29522,29522,29522,29522,29522,29522
Chinese,198,198,198,198,198,198,198,198,198,198,198,198,198,198,198,198,198
Filipino,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213
Guamanian,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20
Hawaiian,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27
Japanese,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73
Korean,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144
Samoan,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42
Vietnamese,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212
White,82499,82499,82499,82499,82499,82499,82499,82499,82499,82499,82499,82499,82499,82499,82499,82499,82499

In [34]:
guns15_17bypa = guns15_17byrace["Manner_Of_Death"].value_counts()

In [35]:
guns15_17bypa

Race                       Manner_Of_Death
American Indian            Suicide                    677
                           Homicide                   531
                           Could not determine         28
                           Accident                    27
                           Pending investigation        7
                           Natural                      1
Asian Indian               Suicide                    123
                           Homicide                   100
                           Could not determine          2
                           Accident                     1
Asian or Pacific Islander  Suicide                    323
                           Homicide                   277
                           Accident                    10
                           Could not determine          4
                           Natural                      2
                           Pending investigation        2
Black                      Homicide                 24957
                           Suicide                   4056
                           Accident                   244
                           Could not determine        192
                           Pending investigation       42
                           Natural                     21
                           Unknown                     10
Chinese                    Suicide                    119
                           Homicide                    75
                           Could not determine          2
                           Accident                     1
                           Pending investigation        1
Filipino                   Suicide                    155
                           Homicide                    55
                           Accident                     2
                           Could not determine          1
Guamanian                  Homicide                    10
                           Suicide                     10
Hawaiian                   Suicide                     17
                           Homicide                    10
Japanese                   Suicide                     57
                           Homicide                    15
                           Accident                     1
Korean                     Suicide                    105
                           Homicide                    38
                           Pending investigation        1
Samoan                     Homicide                    25
                           Suicide                     12
                           Accident                     5
Vietnamese                 Suicide                    115
                           Homicide                    96
                           Could not determine          1
White                      Suicide                  63181
                           Homicide                 17509
                           Accident                   904
                           Could not determine        656
                           Pending investigation      129
                           Natural                     73
                           Unknown                     47
Name: Manner_Of_Death, dtype: int64